{
  "id": "uno-ooo-parser",
  "version": "0.1.5",
  "timestamp": "2021-12-25 14:31:25+00:00",
  "name": "UndoFailedException",
  "type": "exception",
  "namespace": "com.sun.star.document",
  "parser_args": {
    "sort": true
  },
  "writer_args": {
    "include_desc": true
  },
  "data": {
    "from_imports": [
      [
        "..uno.exception",
        "Exception"
      ]
    ],
    "from_imports_typing": [],
    "name": "UndoFailedException",
    "namespace": "com.sun.star.document",
    "imports": [],
    "extends": [
      "com.sun.star.uno.Exception"
    ],
    "desc": [
      "thrown when reverting to re-applying an undoable action fails.",
      "",
      "**Since**",
      "",
      "   OOo 3.4"
    ],
    "url": "https://api.libreoffice.org/docs/idl/ref/exceptioncom_1_1sun_1_1star_1_1document_1_1UndoFailedException.html",
    "items": {
      "properties": [
        {
          "name": "Reason",
          "type": "object",
          "desc": [
            "describes the reason why the operation failed.",
            "",
            "Usually, this member will carry an exception."
          ]
        }
      ]
    }
  }
}