{
  "id": "uno-ooo-parser",
  "version": "0.1.28",
  "libre_office_ver": "7.2",
  "name": "PDFExportException",
  "type": "exception",
  "namespace": "com.sun.star.task",
  "parser_args": {
    "sort": false,
    "long_names": true,
    "remove_parent_inherited": true
  },
  "writer_args": {
    "include_desc": true
  },
  "data": {
    "allow_db": true,
    "from_imports": [
      [
        "..uno.exception",
        "Exception",
        "Exception_85530a09"
      ]
    ],
    "from_imports_typing": [],
    "extends_map": {
      "com.sun.star.uno.Exception": "Exception_85530a09"
    },
    "quote": [
      "typing.Tuple[int, ...]"
    ],
    "typings": [
      "typing.Tuple[int, ...]"
    ],
    "requires_typing": true,
    "full_imports": {
      "general": [
        "com.sun.star.uno.Exception"
      ],
      "typing": []
    },
    "name": "PDFExportException",
    "imports": [],
    "namespace": "com.sun.star.task",
    "extends": [
      "com.sun.star.uno.Exception"
    ],
    "desc": [
      "is an exception that provides information on an error during PDF export."
    ],
    "url": "https://api.libreoffice.org/docs/idl/ref/exceptioncom_1_1sun_1_1star_1_1task_1_1PDFExportException.html",
    "items": {
      "types": [
        {
          "name": "ErrorCodes",
          "returns": "typing.Tuple[int, ...]",
          "origtype": null,
          "origin": "sequence< long >",
          "desc": [
            "contains a number of errors that occurred during PDFExport"
          ],
          "raises_get": "",
          "raises_set": ""
        }
      ]
    }
  }
}