{
  "id": "uno-ooo-parser",
  "version": "0.2.0",
  "libre_office_ver": "7.3",
  "name": "UndoFailedException",
  "type": "exception",
  "namespace": "com.sun.star.document",
  "parser_args": {
    "sort": false,
    "long_names": true,
    "remove_parent_inherited": true
  },
  "writer_args": {
    "include_desc": true
  },
  "data": {
    "allow_db": true,
    "from_imports": [
      [
        "..uno.exception",
        "Exception",
        "Exception_85530a09"
      ]
    ],
    "from_imports_typing": [],
    "extends_map": {
      "com.sun.star.uno.Exception": "Exception_85530a09"
    },
    "quote": [],
    "typings": [],
    "requires_typing": false,
    "full_imports": {
      "general": [
        "com.sun.star.uno.Exception"
      ],
      "typing": []
    },
    "name": "UndoFailedException",
    "imports": [],
    "namespace": "com.sun.star.document",
    "extends": [
      "com.sun.star.uno.Exception"
    ],
    "desc": [
      "thrown when reverting to re-applying an undoable action fails.",
      "",
      "**since**",
      "",
      "    OOo 3.4"
    ],
    "url": "https://api.libreoffice.org/docs/idl/ref/exceptioncom_1_1sun_1_1star_1_1document_1_1UndoFailedException.html",
    "items": {
      "properties": [
        {
          "name": "Reason",
          "returns": "object",
          "origtype": null,
          "origin": "any",
          "desc": [
            "describes the reason why the operation failed.",
            "",
            "Usually, this member will carry an exception."
          ],
          "raises_get": "",
          "raises_set": ""
        }
      ]
    }
  }
}