{
  "id": "uno-ooo-parser",
  "version": "0.1.26",
  "libre_office_ver": "7.2",
  "name": "TerminationVetoException",
  "type": "exception",
  "namespace": "com.sun.star.frame",
  "parser_args": {
    "sort": false,
    "long_names": true,
    "remove_parent_inherited": true
  },
  "writer_args": {
    "include_desc": true
  },
  "data": {
    "allow_db": true,
    "from_imports": [
      [
        "..uno.exception",
        "Exception",
        "Exception_85530a09"
      ]
    ],
    "from_imports_typing": [],
    "extends_map": {
      "com.sun.star.uno.Exception": "Exception_85530a09"
    },
    "quote": [],
    "typings": [],
    "requires_typing": false,
    "full_imports": {
      "general": [
        "com.sun.star.uno.Exception"
      ],
      "typing": []
    },
    "name": "TerminationVetoException",
    "imports": [],
    "namespace": "com.sun.star.frame",
    "extends": [
      "com.sun.star.uno.Exception"
    ],
    "desc": [
      "can be thrown by a XTerminateListener to prevent the environment (e.g., desktop) from terminating",
      "",
      "If a XTerminateListener use this exception for a veto against the termination of the office, he will be the new \\\"owner\\\" of it. After his own operation will be finished, he MUST try to terminate the office again. Any other veto listener can intercept that again or office will die really.",
      "",
      "Since LibreOffice 5.3: Throwing this exception will only prevent termination. Exiting LibreOffice will close all the windows, but the process will keep running."
    ],
    "url": "https://api.libreoffice.org/docs/idl/ref/exceptioncom_1_1sun_1_1star_1_1frame_1_1TerminationVetoException.html",
    "items": {}
  }
}