{
  "id": "uno-ooo-parser",
  "version": "0.2.15",
  "libre_office_ver": "7.4",
  "name": "LdapGenericException",
  "type": "exception",
  "namespace": "com.sun.star.ldap",
  "parser_args": {
    "sort": false,
    "long_names": true,
    "remove_parent_inherited": true
  },
  "writer_args": {
    "include_desc": true
  },
  "data": {
    "allow_db": true,
    "from_imports": [
      [
        "..uno.exception",
        "Exception",
        "Exception_85530a09"
      ]
    ],
    "from_imports_typing": [],
    "extends_map": {
      "com.sun.star.uno.Exception": "Exception_85530a09"
    },
    "quote": [],
    "typings": [],
    "requires_typing": false,
    "full_imports": {
      "general": [
        "com.sun.star.uno.Exception"
      ],
      "typing": []
    },
    "imports": [],
    "name": "LdapGenericException",
    "namespace": "com.sun.star.ldap",
    "extends": [
      "com.sun.star.uno.Exception"
    ],
    "desc": [
      "Generic exception occurring during access to an LDAP server.",
      "",
      "The actual LDAP error code is provided for more refined error management.",
      "",
      "**since**",
      "",
      "    OOo 1.1.2"
    ],
    "url": "https://api.libreoffice.org/docs/idl/ref/exceptioncom_1_1sun_1_1star_1_1ldap_1_1LdapGenericException.html",
    "items": {
      "properties": [
        {
          "name": "ErrorCode",
          "returns": "int",
          "origtype": null,
          "origin": "long",
          "desc": [
            "LDAP error code, see LDAP SDK documentation for complete list of possible values and their meaning."
          ],
          "raises_get": "",
          "raises_set": ""
        }
      ]
    }
  }
}