{
  "id": "uno-ooo-parser",
  "version": "0.2.9",
  "libre_office_ver": "7.3",
  "name": "BridgeExistsException",
  "type": "exception",
  "namespace": "com.sun.star.bridge",
  "parser_args": {
    "sort": false,
    "long_names": true,
    "remove_parent_inherited": true
  },
  "writer_args": {
    "include_desc": true
  },
  "data": {
    "allow_db": true,
    "from_imports": [
      [
        "..uno.exception",
        "Exception",
        "Exception_85530a09"
      ]
    ],
    "from_imports_typing": [],
    "extends_map": {
      "com.sun.star.uno.Exception": "Exception_85530a09"
    },
    "quote": [],
    "typings": [],
    "requires_typing": false,
    "full_imports": {
      "general": [
        "com.sun.star.uno.Exception"
      ],
      "typing": []
    },
    "imports": [],
    "name": "BridgeExistsException",
    "namespace": "com.sun.star.bridge",
    "extends": [
      "com.sun.star.uno.Exception"
    ],
    "desc": [
      "Indicates, that it was tried to create a remote bridge with a name, which already existed."
    ],
    "url": "https://api.libreoffice.org/docs/idl/ref/exceptioncom_1_1sun_1_1star_1_1bridge_1_1BridgeExistsException.html",
    "items": {}
  }
}